### ISSUE TITLE
COCOA-cls annotation

### ISSUE THREAD

**Issue by mingheyuemankong** [YutingXiao/Amodal-Segmentation-Based-on-Visible-Region-Segmentation-and-Shape-Prior#17]
Hi, the number of images in the training set in the COCOA-cls annotation I obtained is 2276, not 2476 as described in your paper?Which value is the accurate one? I am looking forward to get a reply from the author.

**Comment by YutingXiao** [comment]
It is 2276

**Comment by mingheyuemankong** [comment]
Thank you very much for your answer.
