### ISSUE TITLE
Can you provide the download link of BaiduYun or GoogleDrive for D2SA?

### ISSUE THREAD

**Issue by zhixuanli** [YutingXiao/Amodal-Segmentation-Based-on-Visible-Region-Segmentation-and-Shape-Prior#2]
Hi,

I'm trying to download the annotations and images from the D2SA official website. However, after trying several times, the same error message `You don't have the right to access this website` continuously come to me.

```
Images: ftp://guest:GU.205dldo@ftp.softronics.ch/mvtec_d2s/amodal/d2s_amodal_images_v1.tar.xz

Amodal Annotations: ftp://guest:GU.205dldo@ftp.softronics.ch/mvtec_d2s/amodal/d2s_amodal_annotations_v1.tar.xz

```
Can you provide the download link of BaiduYun or GoogleDrive for D2SA?

Thanks a lot!

**Comment by YutingXiao** [comment]
Maybe you should register first.

You can download D2SA dataset at https://www.mvtec.com/company/research/datasets/mvtec-d2s/

**Comment by zhixuanli** [comment]
I have fixed this problem through the powerful TAOBAO, hahahaha

Thank you!
