### ISSUE TITLE
hi, where can i find this paper's supplementary? 

### ISSUE THREAD

**Issue by zzq96** [YutingXiao/Amodal-Segmentation-Based-on-Visible-Region-Segmentation-and-Shape-Prior#9]
I have searched the AAAI digital library, but didnt find it .
Can you provide the download link of this supplementary?
thanks a lot!

**Comment by YutingXiao** [comment]
Hi, this is the supplementary.
[AAAI_supplementary_2021.pdf](https://github.com/YutingXiao/Amodal-Segmentation-Based-on-Visible-Region-Segmentation-and-Shape-Prior/files/6758477/AAAI_supplementary_2021.pdf)
